version: '3.8'

services:
  advertisement_db:
    image: postgres:15
    environment:
      POSTGRES_DB: advertisement_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - advertisement_data:/var/lib/postgresql/data

  message_db:
    image: postgres:15
    environment:
      POSTGRES_DB: message_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - message_data:/var/lib/postgresql/data

  advertisement_service:
    build: ./advertisement_service
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_URL=postgresql://user:password@advertisement_db:5432/advertisement_db
    depends_on:
      - advertisement_db

  message_service:
    build: ./message_service
    ports:
      - "8001:8001"
    environment:
      - POSTGRES_URL=postgresql://user:password@message_db:5432/message_db
    depends_on:
      - message_db

volumes:
  advertisement_data:
  message_data: