server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: advertisement_service
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
    relabel_configs:
      # Фильтруем по label job=advertisement_service
      - source_labels: ['__meta_docker_container_label_job']
        regex: 'advertisement_service'
        action: keep
      # Устанавливаем имя job в Loki
      - target_label: job
        replacement: advertisement_service
      # Добавляем имя контейнера как label
      - source_labels: ['__meta_docker_container_name']
        target_label: container