name: CI/CD to Yandex Serverless (message_service)

on:
  push:
    branches: ["main", "master"]
    paths:
      - 'message_service/**'
      - '.github/workflows/message-service.yml'
  pull_request:
    branches: ["main", "master"]
    paths:
      - 'message_service/**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to YC Container Registry
        uses: docker/login-action@v3
        with:
          registry: cr.yandex
          username: json_key
          password: ${{ secrets.YC_KEYS }}

      - name: Build and push Docker image
        run: |
          docker build -t cr.yandex/${{ secrets.YC_REGISTRY_ID }}/message-service:latest ./message_service
          docker push cr.yandex/${{ secrets.YC_REGISTRY_ID }}/message-service:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Deploy to Yandex Serverless Container
        uses: yc-actions/yc-sls-container-deploy@v1
        with:
          yc-sa-json-credentials: ${{ secrets.YC_KEYS }}
          container-name: ${{ secrets.YC_CONTAINER_NAME }}
          folder-id: ${{ secrets.YC_FOLDER_ID }}
          revision-image-url: cr.yandex/${{ secrets.YC_REGISTRY_ID }}/message-service:latest
          revision-service-account-id: ${{ secrets.YC_SA_ID }}
          revision-cores: 1
          revision-memory: 512Mb
          revision-env: |
            POSTGRES_HOST=51.250.26.59
            POSTGRES_PORT=5432
            POSTGRES_DB=message_db
            POSTGRES_USER=secUREusER
            POSTGRES_PASSWORD=StrongEnoughPassword
            LOG_LEVEL=INFO